Redis(Cache) now (re)supports function as a key_prefix
pallets-eco/cachelib pull request #332
Opened 2024-01-08 14:44 UTC by dbascoules

- Behaviour added here : https://github.com/pallets-eco/flask-caching/pull/109
 - Behaviour removed here : https://github.com/pallets-eco/flask-caching/pull/308/files#diff-d15a59e5c66734a6b6d638efe7582b3a147d5a4213dc3b3ca4e3672c50607ae1

- fixes #331

2024-02-10 15:16 UTC, northernSage commented
Hey @dbascoules, thanks for taking the time to open the PR. Changes seem good overall, we are just a short of a test case covering the new feature. Would you mind adding one? (just let me know if you can't I'll pick it up, no worries).

2024-02-10 15:17 UTC, northernSage requested changes

2024-02-10 15:17 UTC, northernSage commented on src/cachelib/redis.py
> +            self.key_prefix if isinstance(self.key_prefix, str) else self.key_prefix()
Not really an issue here, but I wonder if using On a side note, I wonder if using https://docs.python.org/3/library/functions.html#callable wouldn't be make more sense semantically. In the end we want to call the key if it's callable and use it as is if it's not

2024-02-10 15:56 UTC, closed without merging

2024-02-10 16:08 UTC, northernSage commented
close in favour of #332 with a more descriptive branch naming

2024-02-11 10:06 UTC, dbascoules commented
Thank you for your review and maintaining this library.